### PR TITLE
Migrate to latest deps (axum, hyper, etc.)

### PR DESCRIPTION
**Pull request by kcking**
PENDING lambda-http update, opening as draft for now

### CODE REVIEW

**Comment by kcking** [comment]
Waiting on https://github.com/awslabs/aws-lambda-rust-runtime/pull/749 to be merged

**Comment by lazear** [comment]
Thanks - I was wondering what the best way to support axum 0.7 is: (a) just mandate that all future versions of this crate depend on 0.7, or (b) to select axum/hyper versions via features (I've seen a few other crates do this). The surface area of this crate is super tiny though, so I think it's probably ok to go with route (a). If you have thoughts, happy to hear them!

**Comment by kcking** [comment]
My first thought would be to increment the minor version of this crate to 0.6.x to signify a backwards-incompatible change upon merging this PR. Then if there are any bugs or significant features that make sense to add to older versions, those could be back-ported on a 0.5.x branch.

**Comment by lazear** [comment]
Sounds good - lemme know when ready to merge and I'll pull the trigger!

**Comment by vagmi** [comment]
Thanks for this. I think https://github.com/awslabs/aws-lambda-rust-runtime/pull/749 has been merged. It would be really cool to have a new release of axum-aws-lambda.

**Comment by kcking** [comment]
I just saw that a new lambda-http version was published to crates.io. This is now ready for review @lazear :)

**Pull request merged**
